### PR TITLE
fixes for macOS - closes #1

### LINKED ISSUE #1: Trying to get examples to run on macOS.
Hey @patriciogonzalezvivo 
I gave the instructions a try with the nightly build of OF on macOS 

Nothing seemed to render as is, but I also didn't get any error messages. 

Changing the GL version to 3.2 or 4.1 gave me useful error messages, but didn't change the visual output. 

This is what I changed the main.cpp to ( otherwise it is using the non-programmable renderer )

	//Use ofGLFWWindowSettings for more options like multi-monitor fullscreen
	ofGLWindowSettings settings;
	settings.setSize(1024, 768);
	settings.windowMode = OF_WINDOW; //can also be OF_FULLSCREEN
	settings.setGLVersion(3, 2);
	auto window = ofCreateWindow(settings);

	ofRunApp(window, make_shared<ofApp>());
	ofRunMainLoop();

then the errors I get:

```
[ error ] ofShader: setupShaderFromSource(): GL_VERTEX_SHADER shader failed to compile
[ error ] ofShader: GL_VERTEX_SHADER shader reports:
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:5: 'attribute' : syntax error: syntax error

[ error ] ofShader: GL_VERTEX_SHADER, offending line 1:
	    1	uniform mat4    modelViewProjectionMatrix;
	    2	
	    3	uniform vec2    u_resolution;

[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:2: '' :  #version required and missing.

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 2:
	    1	
	    2	#ifdef GL_ES
	    3	precision highp float;
	    4	#endif

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
ERROR: One or more attached shaders not successfully compiled

[ error ] ofShader: setupShaderFromSource(): GL_VERTEX_SHADER shader failed to compile
[ error ] ofShader: GL_VERTEX_SHADER shader reports:
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:5: 'attribute' : syntax error: syntax error

[ error ] ofShader: GL_VERTEX_SHADER, offending line 1:
	    1	uniform mat4    modelViewProjectionMatrix;
	    2	
	    3	uniform vec2    u_resolution;

[ error ] ofShader: setupShaderFromSource(): GL_FRAGMENT_SHADER shader failed to compile
[ error ] ofShader: GL_FRAGMENT_SHADER shader reports:
ERROR: 0:2: '' :  #version required and missing.

[ error ] ofShader: GL_FRAGMENT_SHADER, offending line 2:
	    1	
	    2	#ifdef GL_ES
	    3	precision mediump float;
	    4	#endif

[ error ] ofShader: checkProgramLinkStatus(): program failed to link
[ error ] ofShader: ofShader: program reports:
ERROR: One or more attached shaders not successfully compiled
```

Is there a specific version of OpenGL I should be setting and if so do we need to inject 
`#version 150` 
or
`#version 410` etc into the lygia shaders  

When I get the shader error I do see a tiny white dot at the screen center - I think it is because the billboard mesh is in normalized coords where as OF would need screen res coords: 

ie: instead of this being -1 to 1 it should be -ofGetWidth()/2 to ofGetWidth()/2 
https://github.com/patriciogonzalezvivo/lygia_of_examples/blob/main/src/ofApp.cpp#L19-L31

Maybe I am missing something basic though. 
What was the setup you used?

### PR DESCRIPTION
**Pull request by ofTheo**
closes #1

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Thank you!!

**Comment by patriciogonzalezvivo** [comment]
Screenshot from 2022-10-30 14-07-11

Horray! now it's cross platform : P

**Comment by ofTheo** [comment]
🤘😁
Super awesome. I love these examples.

**Comment by patriciogonzalezvivo** [comment]
I'm adding them to the website https://lygia.xyz/ If you think on a simple but useful example... or something simple but poetic I would love to feature it.
Thanks for fixing the MacOS build

**Pull request merged**
